name: Release that
on: [push]
jobs:
  release-that:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - uses: rlespinasse/github-slug-action@v4

      - name: Release That Frontend
        uses: rlespinasse/release-that@working-directory
        with:
          working-directory: frontend
          dry-run: true
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Release That Backend
        uses: rlespinasse/release-that@working-directory
        with:
          working-directory: backend
          dry-run: true
          github-token: ${{ secrets.GH_TOKEN }}

      #- name: Release That
      #  uses: rlespinasse/release-that@working-directory
      #  with:
      #    github-token: ${{ secrets.GH_TOKEN }}
