name: Release that
on: [push]
jobs:
  release-that:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - uses: rlespinasse/github-slug-action@github-ref-point

      - name: Print slug variables
        run: |
          echo "Repository: ${{ env.GITHUB_REPOSITORY_SLUG }}"
          echo "Branch Name: ${{ env.GITHUB_REF_NAME }}"
          echo "Branch Point: ${{ env.GITHUB_REF_POINT }}"
          echo "Branch Ref: ${{ env.GITHUB_REF_SLUG }}"
          echo "SHA: ${{ env.GITHUB_SHA_SHORT }}"
        shell: bash

      - name: Release That Frontend
        uses: rlespinasse/release-that@working-directory
        with:
          working-directory: frontend
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Release That Backend
        uses: rlespinasse/release-that@working-directory
        with:
          working-directory: backend
          github-token: ${{ secrets.GH_TOKEN }}

      #- name: Release That
      #  uses: rlespinasse/release-that@working-directory
      #  with:
      #    github-token: ${{ secrets.GH_TOKEN }}
