name: Test Env Behavior
on: [push]
jobs:
  env-behavior-with-slugify-value-used-multiple-times:
    runs-on: ubuntu-latest
    steps:
      - name: use slugify-value with publish-env=true
        uses: rlespinasse/slugify-value@v1
        with:
          key: PUBLISHED_KEY_NAME
          value: PUBLISHED_VALUE
          publish-env: true
          
      - name: use slugify-value with publish-env=true
        uses: rlespinasse/slugify-value@v1
        with:
          key: ANOTHER_PUBLISHED_KEY_NAME
          value: ANOTHER_PUBLISHED_VALUE
          publish-env: true
          
  env-behavior:
    runs-on: ubuntu-latest
    steps:
      - name: Manually set up some custom env var
        run: echo "SOME_ENV_KEY=SOME_ENV_VALUE" >> "$GITHUB_ENV"
        shell: bash

      - name: Another manually set up some custom env var
        run: echo "ANOTHER_ENV_KEY=ANOTHER_ENV_VALUE" >> "$GITHUB_ENV"
        shell: bash

  env-behavior-with-slugify-value-using-publish-env:
    runs-on: ubuntu-latest
    steps:
      - name: Manually set up some custom env var
        run: echo "SOME_ENV_KEY=SOME_ENV_VALUE" >> "$GITHUB_ENV"
        shell: bash

      - name: use slugify-value with publish-env=true
        uses: rlespinasse/slugify-value@v1
        with:
          key: PUBLISHED_KEY_NAME
          value: PUBLISHED_VALUE
          publish-env: true

  env-behavior-with-slugify-value:
    runs-on: ubuntu-latest
    steps:
      - name: Manually set up some custom env var
        run: echo "SOME_ENV_KEY=SOME_ENV_VALUE" >> "$GITHUB_ENV"
        shell: bash

      - name: use slugify-value with publish-env=false
        uses: rlespinasse/slugify-value@v1
        with:
          key: PUBLISHED_KEY_NAME
          value: PUBLISHED_VALUE
          publish-env: false
